---
- name: Converge
  hosts: all
  become: true

  pre_tasks:
    - name: Include variables.
      include_vars: 'vars/main.yml'

  tasks:
    - name: "Include ansible-role-setup_users"
      include_role:
        name: "ansible-role-setup_users"
